version: "3.8"
services:
  db:
    image: "postgres:12"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=admin2021
      - POSTGRES_DB=home_resource_planning
  api:
    image: "hrp_api"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:80
