version: "3"
services:
  db:
    image: "postgres:14"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=admin2021
      - POSTGRES_DB=home_resource_planning
    restart: always

  api:
    image: "hrp_api"
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    ports:
      - 8080:80
    depends_on:
      - db
