version: "3.8"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=admin2021
      - POSTGRES_DB=home_resource_planning
  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: home_resource_planning_api
      image: home_resource_planning_api
      ports:
        - 8080:80
