version: "3.8"
services:
  db:
    image: "postgres:13"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=admin2021
      - POSTGRES_DB=home_resource_planning
  api:
    image: "hrp_api"
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    ports:
      - 8080:80
